 name: dockerAction

 on:
   push:

 jobs:
  test-docker-action:
   name: job to test our docker action
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@5
    - run: chmod +x entrypoint.sh
    - uses: ./
      id: dockerAction
      with:
       number1: 4
       number2: 2
    - run: echo ${{ steps.dockerAction.output.result }}
    - run: cat $GITHUB_WORKSPACE/containerOutputFile.txt
    - run: cat ${{ github.workspace }}/containerOutputFile.txt
    
    

